name = "kobo99-calendar"
main = "src/index.js"
compatibility_date = "2022-06-10"

# [secrets]
# GOOGLE_CLOUD_CREDENTIALS

[vars]
CALENDAR_ID = "rqcl9m6ucfca9vp67afvi3bdhk@group.calendar.google.com"

[env.production.vars]
CALENDAR_ID = "rcmvnfej75s7c9sjdbic1f55v8@group.calendar.google.com"

[env.production.triggers]
crons = [ "20 1,2 * * WED" ]